#!/usr/bin/env python3
"""Generate deterministic, repository-owned visual meshes for Gazebo.

The detailed meshes are visual-only. SDF models keep small primitive collision
shapes so fleet-scale physics remains deterministic and inexpensive.
"""

from __future__ import annotations

import math
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[2]
MESH_DIRECTORY = (
    REPOSITORY
    / "simulation"
    / "ros2_ws"
    / "src"
    / "kinesis_gazebo"
    / "models"
    / "kinesis_amr"
    / "meshes"
)


def rounded_box(
    path: Path,
    *,
    length: float,
    width: float,
    height: float,
    radius: float,
    corner_segments: int = 20,
) -> None:
    """Write a smooth rounded-rectangle extrusion as a Wavefront OBJ."""
    half_x = length / 2
    half_y = width / 2
    half_z = height / 2
    centers = (
        (half_x - radius, half_y - radius, 0.0),
        (-half_x + radius, half_y - radius, math.pi / 2),
        (-half_x + radius, -half_y + radius, math.pi),
        (half_x - radius, -half_y + radius, 3 * math.pi / 2),
    )
    contour = []
    for center_x, center_y, start_angle in centers:
        for step in range(corner_segments + 1):
            angle = start_angle + step * math.pi / (2 * corner_segments)
            contour.append(
                (
                    center_x + radius * math.cos(angle),
                    center_y + radius * math.sin(angle),
                )
            )

    vertices = [(x, y, -half_z) for x, y in contour]
    vertices.extend((x, y, half_z) for x, y in contour)
    vertices.extend(((0.0, 0.0, -half_z), (0.0, 0.0, half_z)))
    count = len(contour)
    bottom_center = 2 * count + 1
    top_center = bottom_center + 1

    lines = [
        "# Generated by simulation/tools/generate_visual_meshes.py",
        "# Visual mesh only; do not use as collision geometry.",
        "o kinesis_amr_shell",
    ]
    lines.extend(f"v {x:.8f} {y:.8f} {z:.8f}" for x, y, z in vertices)
    lines.append("s 1")
    for index in range(count):
        current = index + 1
        following = (index + 1) % count + 1
        lines.append(
            f"f {current} {following} {following + count} {current + count}"
        )
        lines.append(f"f {bottom_center} {following} {current}")
        lines.append(f"f {top_center} {current + count} {following + count}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rounded_box(
        MESH_DIRECTORY / "amr_shell.obj",
        length=0.94,
        width=0.74,
        height=0.28,
        radius=0.12,
        corner_segments=24,
    )


if __name__ == "__main__":
    main()
